# Build throwaway videos for reproducing seek-strip reports (memory / cell count).
#
# These are test assets, not product files. They go outside the repo so a stray
# 4.5 GB file never lands in git.
#
# Needs an ffmpeg.exe with hevc_nvenc on PATH, or pass -FfmpegPath.
# The GPL gyan.dev build is fine here: nothing generated by this script ships.
# It has nothing to do with the LGPL build vendored under vendor/ffmpeg.
#
#   .\scripts\make-seek-strip-test-videos.ps1                 # all three
#   .\scripts\make-seek-strip-test-videos.ps1 -Only Huge360   # just the 4.5 GB one
#
[CmdletBinding()]
param(
    [string]$OutDir = 'C:\tmp\miv-strip-test',
    [ValidateSet('All', 'Huge360', 'Half', 'Long')]
    [string]$Only = 'All',
    [string]$FfmpegPath
)

$ErrorActionPreference = 'Stop'

function Resolve-Ffmpeg {
    param([string]$Explicit)
    if ($Explicit) {
        if (-not (Test-Path $Explicit)) { throw "ffmpeg not found: $Explicit" }
        return $Explicit
    }
    $cmd = Get-Command ffmpeg -ErrorAction SilentlyContinue
    if ($cmd) { return $cmd.Source }
    $winget = Join-Path $env:LOCALAPPDATA 'Microsoft\WinGet\Packages'
    if (Test-Path $winget) {
        $found = Get-ChildItem $winget -Recurse -Filter ffmpeg.exe -ErrorAction SilentlyContinue |
            Select-Object -First 1
        if ($found) { return $found.FullName }
    }
    throw 'ffmpeg.exe not found. Install one (winget install Gyan.FFmpeg) or pass -FfmpegPath.'
}

$ffmpeg = Resolve-Ffmpeg -Explicit $FfmpegPath
Write-Host "ffmpeg: $ffmpeg"
if (-not (Test-Path $OutDir)) { New-Item -ItemType Directory -Force -Path $OutDir | Out-Null }

function Invoke-Ffmpeg {
    param([string[]]$FfArgs, [string]$What)
    Write-Host ""
    Write-Host "== $What"
    & $ffmpeg @FfArgs
    if ($LASTEXITCODE -ne 0) { throw "$What failed (exit $LASTEXITCODE)" }
}

# A stamped source so every strip cell is visually distinct: the burnt-in time
# says which second a cell actually landed on, which is the whole question in
# the "fewer thumbnails" report.
#
# fontfile is spelled out because this build has no fontconfig, and the colon is
# escaped because the filter parser splits options on it.
function Get-StampedInput {
    param([string]$Size, [int]$Rate, [int]$Seconds, [switch]$NoStamp)
    # A tone rather than silence, so the waveform strip has something to draw.
    $inputArgs = @(
        '-f', 'lavfi', '-i', "testsrc2=size=${Size}:rate=${Rate}",
        '-f', 'lavfi', '-i', 'sine=frequency=440:sample_rate=48000',
        '-t', "$Seconds"
    )
    if ($NoStamp) { return $inputArgs }
    $draw = "drawtext=fontfile='C\:/Windows/Fonts/arial.ttf':text='%{pts\:hms}'" +
        ':fontsize=160:fontcolor=white:box=1:boxcolor=black@0.6:x=(w-tw)/2:y=(h-th)/2'
    return $inputArgs + @('-vf', $draw)
}

# 1. The reported case: 5760x2880 (exactly 2:1, so mIV treats it as 360), HEVC,
#    about 4.5 GB. -fs stops at the byte budget, so the duration falls out of the
#    bitrate rather than being pinned.
#
#    No burnt-in stamp here: drawtext runs on the CPU and a 16.6 Mpixel frame is
#    where it stops keeping up with the encoder. This file answers a memory
#    question, and memory does not care what the picture shows.
if ($Only -in @('All', 'Huge360')) {
    $out = Join-Path $OutDir 'dummy_360_5760x2880.mp4'
    $ffArgs = @('-hide_banner', '-loglevel', 'warning', '-stats') +
        (Get-StampedInput -Size '5760x2880' -Rate 30 -Seconds 600 -NoStamp) +
        @(
            '-fs', '4718592000',
            '-c:v', 'hevc_nvenc', '-preset', 'p4',
            '-rc', 'cbr', '-b:v', '110M', '-maxrate', '110M', '-bufsize', '220M',
            '-g', '150', '-bf', '3', '-pix_fmt', 'yuv420p', '-tag:v', 'hvc1',
            '-c:a', 'aac', '-b:a', '128k',
            '-movflags', '+faststart', '-y', $out
        )
    Invoke-Ffmpeg -FfArgs $ffArgs -What "4.5 GB 5760x2880 HEVC -> $out"
}

# 2 and 3. The pair from the cell-count report: show one whole-span strip on the
#    30 minute file, then open the 2 hour one. Encoded once and repeated with
#    stream copy, so two hours costs seconds instead of minutes.
function New-LongVideo {
    param([int]$Minutes, [string]$Out)
    $seed = Join-Path $OutDir "seed_$([System.IO.Path]::GetFileNameWithoutExtension($Out)).mp4"
    $ffArgs = @('-hide_banner', '-loglevel', 'warning', '-stats') +
        (Get-StampedInput -Size '1920x1080' -Rate 30 -Seconds 60) +
        @(
            '-c:v', 'hevc_nvenc', '-preset', 'p4',
            '-rc', 'vbr', '-b:v', '4M', '-maxrate', '6M', '-bufsize', '12M',
            '-g', '150', '-bf', '3', '-pix_fmt', 'yuv420p', '-tag:v', 'hvc1',
            '-c:a', 'aac', '-b:a', '128k',
            '-y', $seed
        )
    Invoke-Ffmpeg -FfArgs $ffArgs -What "60s seed for $Minutes min -> $seed"

    $list = Join-Path $OutDir 'concat.txt'
    $escaped = $seed -replace '\\', '/'
    $lines = 1..$Minutes | ForEach-Object { "file '$escaped'" }
    # Not Set-Content -Encoding utf8: PowerShell 5.1 writes a BOM there, and the
    # concat demuxer reads it as part of the first keyword ("unknown keyword file").
    [System.IO.File]::WriteAllLines($list, $lines)
    Invoke-Ffmpeg -FfArgs @(
        '-hide_banner', '-loglevel', 'warning', '-stats',
        '-f', 'concat', '-safe', '0', '-i', $list,
        '-c', 'copy', '-movflags', '+faststart', '-y', $Out
    ) -What "$Minutes min by stream copy -> $Out"
    Remove-Item $list -ErrorAction SilentlyContinue
    Remove-Item $seed -ErrorAction SilentlyContinue
}

if ($Only -in @('All', 'Half')) {
    New-LongVideo -Minutes 30 -Out (Join-Path $OutDir 'dummy_30min_1080p.mp4')
}
if ($Only -in @('All', 'Long')) {
    New-LongVideo -Minutes 120 -Out (Join-Path $OutDir 'dummy_2h_1080p.mp4')
}

Write-Host ""
Get-ChildItem $OutDir -Filter *.mp4 |
    Select-Object Name, @{n = 'SizeGB'; e = { [math]::Round($_.Length / 1GB, 2) } } |
    Format-Table -AutoSize
