//! Creative 3D LUT registration, asynchronous loading, and CPU application.
//!
//! Registered entries keep the original user-selected `.cube` path for display
//! and legacy migration, while the app-owned copy lives under
//! `<data_dir>/luts/<entry UUID>.cube`. Parsing and managed-file I/O are always
//! performed on worker threads; the UI and video-presenter threads only use
//! already parsed immutable tables.

use eframe::egui;
use local_adjust_core::CubeLutParams;
use serde::{Deserialize, Serialize};
use std::collections::{HashMap, HashSet};
use std::io::Write;
use std::path::{Path, PathBuf};
use std::sync::{Arc, mpsc};
use uuid::Uuid;

const MAX_CUBE_FILE_BYTES: u64 = 128 * 1024 * 1024;

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize)]
pub struct CreativeLutEntry {
    pub id: Uuid,
    pub name: String,
    pub path: PathBuf,
    #[serde(default)]
    pub builtin: Option<BuiltinCreativeLut>,
}

impl CreativeLutEntry {
    pub fn from_loaded_path_with_id(path: PathBuf, lut: &CubeLutParams, id: Uuid) -> Self {
        let mut entry = Self::from_loaded_path(path, lut);
        entry.id = id;
        entry
    }

    pub fn from_loaded_path(path: PathBuf, lut: &CubeLutParams) -> Self {
        let file_stem = path
            .file_stem()
            .and_then(|value| value.to_str())
            .map(str::trim)
            .filter(|value| !value.is_empty());
        // `.cube` generators frequently write the same generic TITLE
        // ("Generated by Resolve"など) into a whole pack. The source filename
        // is the useful, normally unique display name; TITLE remains parser
        // metadata and is only a fallback for a path without a usable stem.
        let name = file_stem
            .map(str::to_owned)
            .or_else(|| {
                let title = lut.name.trim();
                (!title.is_empty()).then(|| title.to_owned())
            })
            .unwrap_or_else(|| "LUT".to_owned());
        Self {
            id: Uuid::new_v4(),
            name,
            path,
            builtin: None,
        }
    }

    pub fn is_builtin(&self) -> bool {
        self.builtin.is_some()
    }

    pub fn managed_path(&self) -> Option<PathBuf> {
        (!self.is_builtin()).then(|| managed_creative_lut_path(self.id))
    }

    /// Repair names written by the old importer, which preferred a generic
    /// Resolve TITLE over the source filename. User-renamed entries are left
    /// untouched.
    pub fn repair_legacy_generated_name(&mut self) {
        if self.builtin.is_some() || !is_generic_generated_title(&self.name) {
            return;
        }
        if let Some(file_stem) = self
            .path
            .file_stem()
            .and_then(|value| value.to_str())
            .map(str::trim)
            .filter(|value| !value.is_empty())
        {
            self.name = file_stem.to_owned();
        }
    }
}

fn is_generic_generated_title(name: &str) -> bool {
    let name = name.trim();
    name.eq_ignore_ascii_case("Generated by Resolve")
        || name.eq_ignore_ascii_case("Generated by DaVinci Resolve")
}

/// Stable built-in creative looks. These are generated as ordinary 17³ LUT
/// tables, so the CPU still-image path and D3D11 video path use exactly the
/// same sampler as user-provided `.cube` files.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum BuiltinCreativeLut {
    WarmFilm,
    CoolFade,
    TealOrange,
    Vintage,
    MonochromeFilm,
}

impl BuiltinCreativeLut {
    pub const ALL: [Self; 5] = [
        Self::WarmFilm,
        Self::CoolFade,
        Self::TealOrange,
        Self::Vintage,
        Self::MonochromeFilm,
    ];

    pub fn id(self) -> Uuid {
        let suffix = match self {
            Self::WarmFilm => 1,
            Self::CoolFade => 2,
            Self::TealOrange => 3,
            Self::Vintage => 4,
            Self::MonochromeFilm => 5,
        };
        Uuid::from_u128(0x6d49_564c_5554_4000_8000_0000_0000_0000 | suffix)
    }

    pub fn name(self) -> &'static str {
        match self {
            Self::WarmFilm => "ウォームフィルム",
            Self::CoolFade => "クールフェード",
            Self::TealOrange => "シネマティック（Teal & Orange）",
            Self::Vintage => "ヴィンテージ",
            Self::MonochromeFilm => "モノクロフィルム",
        }
    }

    pub fn description(self) -> &'static str {
        match self {
            Self::WarmFilm => "暖色寄りのハイライトと穏やかなフィルム調コントラスト",
            Self::CoolFade => "黒を少し浮かせた、青みのある低彩度ルック",
            Self::TealOrange => "シャドウを青緑、ハイライトを暖色へ寄せるシネマ調",
            Self::Vintage => "彩度とコントラストを抑えた、褪色した写真風",
            Self::MonochromeFilm => "輝度を保ちながら引き締める白黒フィルム調",
        }
    }
}

pub fn builtin_creative_lut_entries() -> Vec<CreativeLutEntry> {
    BuiltinCreativeLut::ALL
        .into_iter()
        .map(|builtin| CreativeLutEntry {
            id: builtin.id(),
            name: builtin.name().to_owned(),
            path: PathBuf::new(),
            builtin: Some(builtin),
        })
        .collect()
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct CreativeLutSelection {
    pub id: Option<Uuid>,
    /// Original pixels and LUT output are linearly mixed by this value.
    pub strength: f32,
}

impl Default for CreativeLutSelection {
    fn default() -> Self {
        Self {
            id: None,
            strength: 1.0,
        }
    }
}

impl CreativeLutSelection {
    pub fn is_identity(&self) -> bool {
        self.id.is_none() || self.strength <= f32::EPSILON
    }

    pub fn sanitize(&mut self) {
        self.strength = self.strength.clamp(0.0, 1.0);
    }
}

/// Video preview adjustments. These are viewer-wide and intentionally carry
/// only the image panel's tone controls plus creative LUT selection.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct VideoAdjustments {
    pub brightness: f32,
    pub contrast: f32,
    pub gamma: f32,
    pub saturation: f32,
    pub temperature: f32,
    pub black_point: u8,
    pub white_point: u8,
    pub midtone: f32,
    pub creative_lut: CreativeLutSelection,
}

impl Default for VideoAdjustments {
    fn default() -> Self {
        Self {
            brightness: 0.0,
            contrast: 0.0,
            gamma: 1.0,
            saturation: 0.0,
            temperature: 0.0,
            black_point: 0,
            white_point: 255,
            midtone: 1.0,
            creative_lut: CreativeLutSelection::default(),
        }
    }
}

impl VideoAdjustments {
    pub fn is_color_identity(&self) -> bool {
        self.brightness == 0.0
            && self.contrast == 0.0
            && self.gamma == 1.0
            && self.saturation == 0.0
            && self.temperature == 0.0
            && self.black_point == 0
            && self.white_point == 255
            && self.midtone == 1.0
    }

    pub fn is_identity(&self) -> bool {
        self.is_color_identity() && self.creative_lut.is_identity()
    }

    pub fn sanitize(&mut self) {
        self.brightness = self.brightness.clamp(-100.0, 100.0);
        self.contrast = self.contrast.clamp(-100.0, 100.0);
        self.gamma = self.gamma.clamp(0.2, 5.0);
        self.saturation = self.saturation.clamp(-100.0, 100.0);
        self.temperature = self.temperature.clamp(-100.0, 100.0);
        if self.white_point <= self.black_point {
            self.white_point = self.black_point.saturating_add(1);
            if self.white_point == self.black_point {
                self.black_point = self.white_point.saturating_sub(1);
            }
        }
        self.midtone = self.midtone.clamp(0.1, 10.0);
        self.creative_lut.sanitize();
    }
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VideoPresetSlot {
    pub name: String,
    pub adjustments: VideoAdjustments,
}

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(default)]
pub struct VideoPresetSlots {
    pub slots: [Option<VideoPresetSlot>; 10],
}

impl Default for VideoPresetSlots {
    fn default() -> Self {
        Self {
            slots: Default::default(),
        }
    }
}

impl VideoPresetSlots {
    pub fn sanitize(&mut self) {
        for slot in self.slots.iter_mut().flatten() {
            slot.adjustments.sanitize();
        }
    }
}

pub type SharedCreativeLut = Arc<CubeLutParams>;

#[derive(Clone, Debug)]
pub struct CreativeLutChoice {
    pub id: Uuid,
    pub name: String,
    pub path: String,
    pub builtin: bool,
    pub loaded: bool,
    pub error: Option<String>,
}

/// Immutable state sent to the native video presenter. The parsed LUT table is
/// shared; no file access or parsing occurs on the presenter thread.
#[derive(Clone, Debug)]
pub struct VideoGradeSnapshot {
    pub adjustments: VideoAdjustments,
    pub choices: Arc<[CreativeLutChoice]>,
    pub lut: Option<SharedCreativeLut>,
    pub slots: Arc<[Option<String>]>,
}

impl Default for VideoGradeSnapshot {
    fn default() -> Self {
        Self {
            adjustments: VideoAdjustments::default(),
            choices: Arc::from([]),
            lut: None,
            slots: vec![None; 10].into(),
        }
    }
}

struct LoadBatch {
    signature: Vec<(Uuid, PathBuf, Option<BuiltinCreativeLut>)>,
    rx: mpsc::Receiver<Vec<(Uuid, Result<CubeLutParams, String>)>>,
}

struct ManagedCopyBatch {
    rx: mpsc::Receiver<Vec<(Uuid, Result<CubeLutParams, String>)>>,
}

/// Runtime cache owned by `App`. File reads and `.cube` parsing happen in one
/// background batch whenever the registered entry signature changes.
/// 読み込み済み LUT の不変スナップショット。worker が params から自分で引く。
#[derive(Clone, Debug, Default)]
pub struct CreativeLutSnapshot {
    loaded: HashMap<Uuid, SharedCreativeLut>,
}

impl CreativeLutSnapshot {
    #[cfg(test)]
    pub(crate) fn from_loaded(loaded: HashMap<Uuid, SharedCreativeLut>) -> Self {
        Self { loaded }
    }

    /// params が指す LUT と強度。identity か、その LUT が読み込めていなければ `None`。
    pub fn resolve(
        &self,
        params: &crate::adjustment::AdjustParams,
    ) -> Option<(SharedCreativeLut, f32)> {
        if params.creative_lut.is_identity() {
            return None;
        }
        let lut = self.loaded.get(&params.creative_lut.id?)?;
        Some((Arc::clone(lut), params.creative_lut.strength))
    }
}

#[derive(Default)]
pub struct CreativeLutLibrary {
    loaded: HashMap<Uuid, SharedCreativeLut>,
    errors: HashMap<Uuid, String>,
    managed_migrated: HashSet<Uuid>,
    signature: Vec<(Uuid, PathBuf, Option<BuiltinCreativeLut>)>,
    pending: Option<LoadBatch>,
    managed_copy_pending: Option<ManagedCopyBatch>,
}

impl CreativeLutLibrary {
    pub fn new(entries: &[CreativeLutEntry]) -> Self {
        let mut this = Self::default();
        this.reload(entries);
        this
    }

    pub fn reload(&mut self, entries: &[CreativeLutEntry]) {
        let signature = entry_signature(entries);
        if self.signature == signature
            && self
                .pending
                .as_ref()
                .is_none_or(|pending| pending.signature == signature)
        {
            return;
        }
        self.signature = signature.clone();
        self.loaded
            .retain(|id, _| signature.iter().any(|(entry_id, _, _)| entry_id == id));
        self.errors
            .retain(|id, _| signature.iter().any(|(entry_id, _, _)| entry_id == id));
        self.managed_migrated
            .retain(|id| signature.iter().any(|(entry_id, _, _)| entry_id == id));

        if signature.is_empty() {
            self.pending = None;
            return;
        }

        let (tx, rx) = mpsc::channel();
        let worker_signature = signature.clone();
        let spawned = std::thread::Builder::new()
            .name("creative-lut-loader".to_owned())
            .spawn(move || {
                let results = worker_signature
                    .iter()
                    .map(|(id, path, builtin)| {
                        (
                            *id,
                            builtin
                                .map(build_builtin_creative_lut)
                                .map(Ok)
                                .unwrap_or_else(|| load_registered_cube_file(*id, path)),
                        )
                    })
                    .collect();
                let _ = tx.send(results);
            });
        match spawned {
            Ok(_) => self.pending = Some(LoadBatch { signature, rx }),
            Err(error) => {
                self.pending = None;
                let message = format!("LUTの読み込みスレッドを開始できません: {error}");
                self.errors.extend(
                    signature
                        .into_iter()
                        .map(|(id, _, _)| (id, message.clone())),
                );
            }
        }
        self.start_managed_copy_migration(entries);
    }

    pub fn poll(&mut self, entries: &[CreativeLutEntry], ctx: &egui::Context) -> bool {
        self.reload(entries);
        let mut changed = false;

        let load_result = self.pending.as_ref().map(|pending| pending.rx.try_recv());
        match load_result {
            Some(Ok(results)) => {
                let pending = self.pending.take().expect("checked above");
                if pending.signature == self.signature {
                    let previous_loaded = std::mem::take(&mut self.loaded);
                    self.errors.clear();
                    for (id, result) in results {
                        match result {
                            Ok(lut) => {
                                self.loaded.insert(id, Arc::new(lut));
                            }
                            Err(error) => {
                                if self.managed_migrated.contains(&id)
                                    && let Some(lut) = previous_loaded.get(&id)
                                {
                                    self.loaded.insert(id, Arc::clone(lut));
                                } else {
                                    self.errors.insert(id, error);
                                }
                            }
                        }
                    }
                    changed = true;
                }
            }
            Some(Err(mpsc::TryRecvError::Disconnected)) => {
                self.pending = None;
            }
            Some(Err(mpsc::TryRecvError::Empty)) | None => {}
        }

        let migration_result = self
            .managed_copy_pending
            .as_ref()
            .map(|pending| pending.rx.try_recv());
        match migration_result {
            Some(Ok(results)) => {
                self.managed_copy_pending = None;
                let registered_ids: HashSet<_> = entries.iter().map(|entry| entry.id).collect();
                let mut stale_ids = Vec::new();
                for (id, result) in results {
                    if !registered_ids.contains(&id) {
                        stale_ids.push(id);
                        continue;
                    }
                    match result {
                        Ok(lut) => {
                            self.loaded.insert(id, Arc::new(lut));
                            self.errors.remove(&id);
                            self.managed_migrated.insert(id);
                            changed = true;
                        }
                        Err(error) => crate::logger::log(format!(
                            "creative LUT managed-copy migration failed for {id}: {error}"
                        )),
                    }
                }
                remove_managed_creative_luts_async(stale_ids);
            }
            Some(Err(mpsc::TryRecvError::Disconnected)) => {
                self.managed_copy_pending = None;
            }
            Some(Err(mpsc::TryRecvError::Empty)) | None => {}
        }

        if changed {
            ctx.request_repaint();
        }
        changed
    }

    fn start_managed_copy_migration(&mut self, entries: &[CreativeLutEntry]) {
        if self.managed_copy_pending.is_some() {
            return;
        }
        let user_entries = entries
            .iter()
            .filter(|entry| !entry.is_builtin())
            .map(|entry| (entry.id, entry.path.clone()))
            .collect::<Vec<_>>();
        if user_entries.is_empty() {
            self.managed_copy_pending = None;
            return;
        }

        let (tx, rx) = mpsc::channel();
        let spawned = std::thread::Builder::new()
            .name("creative-lut-managed-copy".to_owned())
            .spawn(move || {
                let results = user_entries
                    .into_iter()
                    .map(|(id, source_path)| (id, ensure_managed_creative_lut(id, &source_path)))
                    .collect();
                let _ = tx.send(results);
            });
        match spawned {
            Ok(_) => {
                self.managed_copy_pending = Some(ManagedCopyBatch { rx });
            }
            Err(error) => {
                crate::logger::log(format!(
                    "creative LUT managed-copy migration thread failed to start: {error}"
                ));
                self.managed_copy_pending = None;
            }
        }
    }

    pub fn get(&self, id: Option<Uuid>) -> Option<SharedCreativeLut> {
        id.and_then(|id| self.loaded.get(&id).cloned())
    }

    /// worker へ渡す読み込み済み LUT の一覧。
    ///
    /// 値は `Arc` なので clone は参照カウントの加算だけ。**解決済みの 1 本ではなく
    /// 一覧を渡す**のは、どの LUT を使うかが params 側で決まり、その params を worker が
    /// 読み直すことがあるため (v3.5.0 レビュー F10)。
    pub fn snapshot(&self) -> CreativeLutSnapshot {
        CreativeLutSnapshot {
            loaded: self.loaded.clone(),
        }
    }

    pub fn error(&self, id: Uuid) -> Option<&str> {
        self.errors.get(&id).map(String::as_str)
    }

    pub fn loaded_ids(&self) -> HashSet<Uuid> {
        self.loaded.keys().copied().collect()
    }

    pub fn video_snapshot(
        &self,
        entries: &[CreativeLutEntry],
        adjustments: &VideoAdjustments,
        preset_slots: &VideoPresetSlots,
    ) -> VideoGradeSnapshot {
        let choices = entries
            .iter()
            .map(|entry| CreativeLutChoice {
                id: entry.id,
                name: entry.name.clone(),
                path: entry
                    .builtin
                    .map(|builtin| format!("組み込みプリセット: {}", builtin.description()))
                    .unwrap_or_else(|| managed_creative_lut_path(entry.id).display().to_string()),
                builtin: entry.is_builtin(),
                loaded: self.loaded.contains_key(&entry.id),
                error: self.errors.get(&entry.id).cloned(),
            })
            .collect::<Vec<_>>()
            .into();
        VideoGradeSnapshot {
            adjustments: adjustments.clone(),
            choices,
            lut: self.get(adjustments.creative_lut.id),
            slots: preset_slots
                .slots
                .iter()
                .map(|slot| slot.as_ref().map(|slot| slot.name.clone()))
                .collect::<Vec<_>>()
                .into(),
        }
    }
}

/// Load one registered entry without mutating or migrating the library.
///
/// The remote adapter owns its parsed-LUT cache and uses this same parser and
/// built-in generator as the desktop library.
pub(crate) fn load_creative_lut_entry(
    entry: &CreativeLutEntry,
) -> Result<SharedCreativeLut, String> {
    let lut = match entry.builtin {
        Some(builtin) => build_builtin_creative_lut(builtin),
        None => load_registered_cube_file(entry.id, &entry.path)?,
    };
    Ok(Arc::new(lut))
}

fn load_registered_cube_file(id: Uuid, source_path: &Path) -> Result<CubeLutParams, String> {
    let managed_path = managed_creative_lut_path(id);
    match std::fs::metadata(&managed_path) {
        Ok(_) => load_cube_file(&managed_path),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => load_cube_file(source_path),
        Err(error) => Err(format!(
            "{} の情報を取得できません: {error}",
            managed_path.display()
        )),
    }
}

fn ensure_managed_creative_lut(id: Uuid, source_path: &Path) -> Result<CubeLutParams, String> {
    let managed_path = managed_creative_lut_path(id);
    match std::fs::metadata(&managed_path) {
        Ok(_) => return load_cube_file(&managed_path),
        Err(error) if error.kind() == std::io::ErrorKind::NotFound => {}
        Err(error) => {
            return Err(format!(
                "{} の情報を取得できません: {error}",
                managed_path.display()
            ));
        }
    }

    let payload = read_cube_payload(source_path)?;
    write_managed_cube_atomic(&managed_path, &payload.bytes)?;
    Ok(payload.lut)
}

pub struct CreativeLutImport {
    pub entry: CreativeLutEntry,
}

pub fn import_managed_cube_file(path: &Path, id: Uuid) -> Result<CreativeLutImport, String> {
    let payload = read_cube_payload(path)?;
    let target = managed_creative_lut_path(id);
    write_new_managed_cube(&target, &payload.bytes)?;
    Ok(CreativeLutImport {
        entry: CreativeLutEntry::from_loaded_path_with_id(path.to_path_buf(), &payload.lut, id),
    })
}

pub fn managed_creative_lut_dir() -> PathBuf {
    crate::data_dir::get().join("luts")
}

pub fn managed_creative_lut_path(id: Uuid) -> PathBuf {
    managed_creative_lut_dir().join(format!("{id}.cube"))
}

pub fn remove_managed_creative_luts_async(ids: Vec<Uuid>) {
    if ids.is_empty() {
        return;
    }
    let _ = std::thread::Builder::new()
        .name("creative-lut-managed-remove".to_owned())
        .spawn(move || {
            for id in ids {
                if let Err(error) = remove_managed_creative_lut(id)
                    && error.kind() != std::io::ErrorKind::NotFound
                {
                    crate::logger::log(format!(
                        "creative LUT managed copy removal failed for {id}: {error}"
                    ));
                }
            }
        });
}

pub fn remove_managed_creative_lut(id: Uuid) -> std::io::Result<()> {
    std::fs::remove_file(managed_creative_lut_path(id))
}

fn entry_signature(
    entries: &[CreativeLutEntry],
) -> Vec<(Uuid, PathBuf, Option<BuiltinCreativeLut>)> {
    entries
        .iter()
        .map(|entry| (entry.id, entry.path.clone(), entry.builtin))
        .collect()
}

fn build_builtin_creative_lut(builtin: BuiltinCreativeLut) -> CubeLutParams {
    const SIZE: usize = 17;
    let mut table = Vec::with_capacity(SIZE * SIZE * SIZE);
    for b in 0..SIZE {
        for g in 0..SIZE {
            for r in 0..SIZE {
                let denominator = (SIZE - 1) as f32;
                let input = [
                    r as f32 / denominator,
                    g as f32 / denominator,
                    b as f32 / denominator,
                ];
                table.push(apply_builtin_look(builtin, input));
            }
        }
    }
    CubeLutParams {
        name: builtin.name().to_owned(),
        size: SIZE,
        domain_min: [0.0; 3],
        domain_max: [1.0; 3],
        table,
        strength: 1.0,
    }
}

fn apply_builtin_look(builtin: BuiltinCreativeLut, rgb: [f32; 3]) -> [f32; 3] {
    let clamp = |value: f32| value.clamp(0.0, 1.0);
    let contrast = |value: f32, amount: f32| clamp((value - 0.5) * amount + 0.5);
    let saturate = |color: [f32; 3], amount: f32| {
        let luma = color[0] * 0.299 + color[1] * 0.587 + color[2] * 0.114;
        [
            clamp(luma + (color[0] - luma) * amount),
            clamp(luma + (color[1] - luma) * amount),
            clamp(luma + (color[2] - luma) * amount),
        ]
    };
    match builtin {
        BuiltinCreativeLut::WarmFilm => {
            let base = saturate(
                [
                    contrast(rgb[0], 1.06),
                    contrast(rgb[1], 1.04),
                    contrast(rgb[2], 1.02),
                ],
                0.96,
            );
            let light = (base[0] * 0.299 + base[1] * 0.587 + base[2] * 0.114).sqrt();
            [
                clamp(base[0] + 0.030 * light + 0.006),
                clamp(base[1] + 0.010 * light),
                clamp(base[2] - 0.028 * light),
            ]
        }
        BuiltinCreativeLut::CoolFade => {
            let faded = [
                0.035 + rgb[0] * 0.91,
                0.040 + rgb[1] * 0.92,
                0.055 + rgb[2] * 0.93,
            ];
            let base = saturate(faded, 0.88);
            [
                clamp(base[0] * 0.97),
                clamp(base[1] * 1.005),
                clamp(base[2] * 1.035 + 0.008),
            ]
        }
        BuiltinCreativeLut::TealOrange => {
            let base = saturate(
                [
                    contrast(rgb[0], 1.08),
                    contrast(rgb[1], 1.08),
                    contrast(rgb[2], 1.08),
                ],
                1.08,
            );
            let luma = clamp(base[0] * 0.299 + base[1] * 0.587 + base[2] * 0.114);
            let shadow = (1.0 - luma).powf(1.6);
            let highlight = luma.powf(1.6);
            [
                clamp(base[0] + 0.060 * highlight - 0.024 * shadow),
                clamp(base[1] + 0.024 * shadow + 0.008 * highlight),
                clamp(base[2] + 0.052 * shadow - 0.045 * highlight),
            ]
        }
        BuiltinCreativeLut::Vintage => {
            let faded = [
                0.055 + rgb[0] * 0.88,
                0.050 + rgb[1] * 0.87,
                0.042 + rgb[2] * 0.84,
            ];
            let base = saturate(faded, 0.72);
            let sepia = [
                clamp(base[0] * 0.393 + base[1] * 0.769 + base[2] * 0.189),
                clamp(base[0] * 0.349 + base[1] * 0.686 + base[2] * 0.168),
                clamp(base[0] * 0.272 + base[1] * 0.534 + base[2] * 0.131),
            ];
            [
                clamp(base[0] * 0.86 + sepia[0] * 0.14),
                clamp(base[1] * 0.86 + sepia[1] * 0.14),
                clamp(base[2] * 0.86 + sepia[2] * 0.14),
            ]
        }
        BuiltinCreativeLut::MonochromeFilm => {
            let luma = rgb[0] * 0.299 + rgb[1] * 0.587 + rgb[2] * 0.114;
            let value = clamp(contrast(luma, 1.12) * 0.98 + 0.012);
            [value; 3]
        }
    }
}

struct CubePayload {
    lut: CubeLutParams,
    bytes: Vec<u8>,
}

fn read_cube_payload(path: &Path) -> Result<CubePayload, String> {
    let metadata = std::fs::metadata(path)
        .map_err(|error| format!("{} の情報を取得できません: {error}", path.display()))?;
    if metadata.len() > MAX_CUBE_FILE_BYTES {
        return Err(format!(
            "LUTファイルが大きすぎます（上限 {} MiB）",
            MAX_CUBE_FILE_BYTES / 1024 / 1024
        ));
    }
    let bytes = std::fs::read(path)
        .map_err(|error| format!("{} を読み込めません: {error}", path.display()))?;
    if bytes.len() as u64 > MAX_CUBE_FILE_BYTES {
        return Err(format!(
            "LUTファイルが大きすぎます（上限 {} MiB）",
            MAX_CUBE_FILE_BYTES / 1024 / 1024
        ));
    }
    let text = std::str::from_utf8(&bytes)
        .map_err(|error| format!("{} はUTF-8の.cubeではありません: {error}", path.display()))?;
    let fallback = path
        .file_stem()
        .and_then(|value| value.to_str())
        .unwrap_or("LUT");
    let lut = local_adjust_core::parse_cube_lut(text, fallback)?;
    Ok(CubePayload { lut, bytes })
}

fn write_new_managed_cube(path: &Path, bytes: &[u8]) -> Result<(), String> {
    let parent = path
        .parent()
        .ok_or_else(|| "LUTの保存先ディレクトリを決定できません。".to_owned())?;
    std::fs::create_dir_all(parent)
        .map_err(|error| format!("{} を作成できません: {error}", parent.display()))?;
    let mut output = std::fs::OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(path)
        .map_err(|error| format!("{} を作成できません: {error}", path.display()))?;
    if let Err(error) = output.write_all(bytes).and_then(|_| output.sync_data()) {
        drop(output);
        let _ = std::fs::remove_file(path);
        return Err(format!("{} へ保存できません: {error}", path.display()));
    }
    Ok(())
}

fn write_managed_cube_atomic(path: &Path, bytes: &[u8]) -> Result<(), String> {
    let parent = path
        .parent()
        .ok_or_else(|| "LUTの保存先ディレクトリを決定できません。".to_owned())?;
    std::fs::create_dir_all(parent)
        .map_err(|error| format!("{} を作成できません: {error}", parent.display()))?;
    let temp_path = parent.join(format!(".{}.tmp", Uuid::new_v4()));
    write_new_managed_cube(&temp_path, bytes)?;
    if let Err(error) = std::fs::rename(&temp_path, path) {
        let _ = std::fs::remove_file(&temp_path);
        return Err(format!("{} を確定できません: {error}", path.display()));
    }
    Ok(())
}

pub fn load_cube_file(path: &Path) -> Result<CubeLutParams, String> {
    read_cube_payload(path).map(|payload| payload.lut)
}

pub fn apply_to_color_image(
    source: &egui::ColorImage,
    lut: &CubeLutParams,
    strength: f32,
) -> egui::ColorImage {
    let strength = strength.clamp(0.0, 1.0);
    if strength <= f32::EPSILON || !lut.is_loaded() {
        return source.clone();
    }
    let pixels = source
        .pixels
        .iter()
        .map(|pixel| {
            let [r, g, b, a] = pixel.to_srgba_unmultiplied();
            let input = [r as f32 / 255.0, g as f32 / 255.0, b as f32 / 255.0];
            let output = local_adjust_core::sample_cube_lut(lut, input);
            let mix = |original: f32, graded: f32| {
                ((original + (graded - original) * strength).clamp(0.0, 1.0) * 255.0).round() as u8
            };
            egui::Color32::from_rgba_unmultiplied(
                mix(input[0], output[0]),
                mix(input[1], output[1]),
                mix(input[2], output[2]),
                a,
            )
        })
        .collect();
    egui::ColorImage::new(source.size, pixels)
}

#[cfg(test)]
mod tests {
    use super::*;

    const VALID_CUBE: &str = r#"
TITLE "Managed test"
LUT_3D_SIZE 2
0.0 0.0 0.0
1.0 0.0 0.0
0.0 1.0 0.0
1.0 1.0 0.0
0.0 0.0 1.0
1.0 0.0 1.0
0.0 1.0 1.0
1.0 1.0 1.0
"#;

    #[test]
    fn identity_selection_does_not_enable_processing() {
        assert!(CreativeLutSelection::default().is_identity());
        let selection = CreativeLutSelection {
            id: Some(Uuid::new_v4()),
            strength: 0.0,
        };
        assert!(selection.is_identity());
    }

    #[test]
    fn video_adjustment_sanitize_preserves_valid_levels_order() {
        let mut params = VideoAdjustments {
            black_point: 240,
            white_point: 10,
            ..Default::default()
        };
        params.sanitize();
        assert!(params.white_point > params.black_point);
    }

    #[test]
    fn video_preset_slots_serde_round_trip_empty() {
        let slots = VideoPresetSlots::default();
        let json = serde_json::to_string(&slots).expect("serialize empty video preset slots");
        let restored: VideoPresetSlots =
            serde_json::from_str(&json).expect("deserialize empty video preset slots");
        assert_eq!(restored, slots);
    }

    #[test]
    fn video_preset_slots_serde_round_trip_partially_filled() {
        let mut slots = VideoPresetSlots::default();
        slots.slots[0] = Some(VideoPresetSlot {
            name: "明るめ".to_string(),
            adjustments: VideoAdjustments {
                brightness: 24.0,
                contrast: 12.0,
                ..Default::default()
            },
        });
        slots.slots[9] = Some(VideoPresetSlot {
            name: "映画".to_string(),
            adjustments: VideoAdjustments {
                gamma: 1.4,
                saturation: -18.0,
                ..Default::default()
            },
        });

        let json = serde_json::to_string(&slots).expect("serialize populated video preset slots");
        let restored: VideoPresetSlots =
            serde_json::from_str(&json).expect("deserialize populated video preset slots");
        assert_eq!(restored, slots);
    }

    #[test]
    fn builtin_presets_have_stable_unique_ids_and_loaded_tables() {
        let entries = builtin_creative_lut_entries();
        let ids: HashSet<_> = entries.iter().map(|entry| entry.id).collect();
        assert_eq!(entries.len(), BuiltinCreativeLut::ALL.len());
        assert_eq!(ids.len(), entries.len());
        for entry in entries {
            let builtin = entry.builtin.expect("built-in source");
            assert_eq!(entry.id, builtin.id());
            assert_eq!(entry.name, builtin.name());
            assert!(entry.path.as_os_str().is_empty());
            assert!(build_builtin_creative_lut(builtin).is_loaded());
        }
    }

    #[test]
    fn builtin_presets_produce_distinct_looks() {
        let input = [0.24, 0.51, 0.78];
        let outputs: HashSet<_> = BuiltinCreativeLut::ALL
            .into_iter()
            .map(|builtin| {
                let output =
                    local_adjust_core::sample_cube_lut(&build_builtin_creative_lut(builtin), input);
                output.map(|value| (value * 255.0).round() as u8)
            })
            .collect();
        assert_eq!(outputs.len(), BuiltinCreativeLut::ALL.len());

        let monochrome = local_adjust_core::sample_cube_lut(
            &build_builtin_creative_lut(BuiltinCreativeLut::MonochromeFilm),
            input,
        );
        assert_eq!(monochrome[0], monochrome[1]);
        assert_eq!(monochrome[1], monochrome[2]);
    }

    #[test]
    fn legacy_registered_entry_defaults_to_user_file_source() {
        let entry: CreativeLutEntry = serde_json::from_str(
            r#"{"id":"00000000-0000-0000-0000-000000000123","name":"User","path":"look.cube"}"#,
        )
        .expect("legacy entry");
        assert!(!entry.is_builtin());
    }

    #[test]
    fn imported_user_lut_prefers_filename_over_generic_cube_title() {
        let lut = CubeLutParams {
            name: "Generated by Resolve".to_owned(),
            ..Default::default()
        };
        let entry = CreativeLutEntry::from_loaded_path(
            PathBuf::from("DJI OSMO Action 4 Forest Pro.cube"),
            &lut,
        );
        assert_eq!(entry.name, "DJI OSMO Action 4 Forest Pro");
    }

    #[test]
    fn legacy_resolve_name_is_repaired_but_custom_name_is_preserved() {
        let path = PathBuf::from("DJI OSMO Action 4 Ice Pro.cube");
        let mut generated = CreativeLutEntry {
            id: Uuid::from_u128(1),
            name: "Generated by Resolve".to_owned(),
            path: path.clone(),
            builtin: None,
        };
        generated.repair_legacy_generated_name();
        assert_eq!(generated.name, "DJI OSMO Action 4 Ice Pro");

        let mut custom = CreativeLutEntry {
            id: Uuid::from_u128(2),
            name: "My Ice Look".to_owned(),
            path,
            builtin: None,
        };
        custom.repair_legacy_generated_name();
        assert_eq!(custom.name, "My Ice Look");
    }

    #[test]
    fn managed_import_remains_loadable_after_source_is_deleted() {
        let data_dir = crate::data_dir::TestDataDirGuard::new();
        let source = data_dir.path().join("source-look.cube");
        std::fs::write(&source, VALID_CUBE).expect("write source LUT");
        let id = Uuid::new_v4();

        let imported = import_managed_cube_file(&source, id).expect("import LUT");
        let managed = managed_creative_lut_path(id);
        assert_eq!(imported.entry.id, id);
        assert_eq!(
            std::fs::read(&managed).expect("managed copy"),
            VALID_CUBE.as_bytes()
        );

        std::fs::remove_file(&source).expect("remove original");
        assert!(
            load_registered_cube_file(id, &source)
                .expect("load managed copy")
                .is_loaded()
        );
    }

    #[test]
    fn legacy_registration_is_copied_to_managed_storage() {
        let data_dir = crate::data_dir::TestDataDirGuard::new();
        let source = data_dir.path().join("legacy-look.cube");
        std::fs::write(&source, VALID_CUBE).expect("write source LUT");
        let id = Uuid::new_v4();

        assert!(
            ensure_managed_creative_lut(id, &source)
                .expect("migrate legacy LUT")
                .is_loaded()
        );
        std::fs::remove_file(&source).expect("remove original");
        assert!(
            load_registered_cube_file(id, &source)
                .expect("load migrated LUT")
                .is_loaded()
        );
    }

    #[test]
    fn invalid_import_does_not_leave_a_managed_file() {
        let data_dir = crate::data_dir::TestDataDirGuard::new();
        let source = data_dir.path().join("invalid.cube");
        std::fs::write(&source, "LUT_1D_SIZE 2\n0.0\n1.0\n").expect("write invalid LUT");
        let id = Uuid::new_v4();

        assert!(import_managed_cube_file(&source, id).is_err());
        assert!(!managed_creative_lut_path(id).exists());
    }

    #[test]
    fn creative_lut_is_applied_with_strength_and_preserves_alpha() {
        let lut = local_adjust_core::parse_cube_lut(
            r#"
LUT_3D_SIZE 2
1.0 1.0 1.0
0.0 1.0 1.0
1.0 0.0 1.0
0.0 0.0 1.0
1.0 1.0 0.0
0.0 1.0 0.0
1.0 0.0 0.0
0.0 0.0 0.0
"#,
            "invert",
        )
        .expect("valid LUT");
        let source = egui::ColorImage::new(
            [1, 1],
            vec![egui::Color32::from_rgba_unmultiplied(0, 128, 255, 77)],
        );

        let output = apply_to_color_image(&source, &lut, 0.5);
        let [r, g, b, a] = output.pixels[0].to_srgba_unmultiplied();

        assert!((127..=129).contains(&r));
        assert!((127..=129).contains(&g));
        assert!((127..=129).contains(&b));
        assert_eq!(a, 77);
    }
}
