#[path = "src/web_assets.rs"]
mod web_assets;

use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

const GENERATED_ASSETS_FILE: &str = "embedded_web_assets.rs";

fn main() {
    let manifest_dir = PathBuf::from(
        std::env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR is not set"),
    );
    let web_root = manifest_dir.join("web");
    println!("cargo:rerun-if-changed={}", web_root.display());

    let mut assets = Vec::new();
    collect_distribution_assets(&web_root, &web_root, &mut assets);
    assets.sort();

    assert!(
        assets.iter().any(|asset| asset == "index.html"),
        "remote web distribution assets must contain index.html"
    );
    for asset in &assets {
        assert!(
            web_assets::content_type(asset).is_some(),
            "remote web distribution asset has no Content-Type mapping: {asset}"
        );
    }

    let generated = render_assets(&assets);
    let out_dir = PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR is not set"));
    fs::write(out_dir.join(GENERATED_ASSETS_FILE), generated)
        .expect("failed to write generated remote web asset manifest");
}

fn collect_distribution_assets(root: &Path, directory: &Path, assets: &mut Vec<String>) {
    let mut entries: Vec<_> = fs::read_dir(directory)
        .unwrap_or_else(|error| {
            panic!(
                "failed to scan remote web asset directory {}: {error}",
                directory.display()
            )
        })
        .map(|entry| entry.expect("failed to read remote web asset directory entry"))
        .collect();
    entries.sort_by_key(|entry| entry.file_name());

    for entry in entries {
        let file_type = entry.file_type().unwrap_or_else(|error| {
            panic!("failed to inspect {}: {error}", entry.path().display())
        });
        if file_type.is_dir() {
            collect_distribution_assets(root, &entry.path(), assets);
            continue;
        }
        // Symlinks and other special filesystem entries are not distribution assets.
        if !file_type.is_file() {
            continue;
        }

        let relative = entry
            .path()
            .strip_prefix(root)
            .expect("remote web asset escaped its root")
            .to_str()
            .unwrap_or_else(|| {
                panic!(
                    "remote web asset path is not valid UTF-8: {}",
                    entry.path().display()
                )
            })
            .replace('\\', "/");
        if web_assets::is_distribution_asset(&relative) {
            assets.push(relative);
        }
    }
}

fn render_assets(assets: &[String]) -> String {
    let mut generated = String::from(
        "// @generated by crates/remote-web/build.rs; do not edit.\n\
         pub(crate) static WEB_ASSET_PATHS: &[&str] = &[\n",
    );
    for asset in assets {
        writeln!(generated, "    {asset:?},").unwrap();
    }
    generated.push_str("];\n\n");
    generated.push_str(
        "#[cfg(feature = \"embedded-web-assets\")]\n\
         pub(crate) static EMBEDDED_WEB_ASSETS: &[(&str, &[u8])] = &[\n",
    );
    for asset in assets {
        writeln!(
            generated,
            "    ({asset:?}, include_bytes!(concat!(env!(\"CARGO_MANIFEST_DIR\"), \"/web/\", {asset:?}))),"
        )
        .unwrap();
    }
    generated.push_str("];\n");
    generated
}
