//! PNG (and JPEG/GIF/WebP/BMP) → MAG batch converter.
//!
//! Usage:
//!   png2mag <input> <output>
//!     - input: file or directory
//!     - output: directory (created if missing)
//!
//! For directory input, walks recursively, converts each supported image to
//! a 16-color MAG with the same relative path. Width is rounded up to a
//! multiple of 4 by padding the right edge with palette index 0.

use anyhow::{Context, Result, bail};
use rayon::prelude::*;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicUsize, Ordering};

mod encoder;
mod quantize;

const SUPPORTED_EXTS: &[&str] = &["png", "jpg", "jpeg", "gif", "webp", "bmp"];

fn collect_inputs(input: &Path) -> Result<Vec<PathBuf>> {
    let mut out = Vec::new();
    if input.is_file() {
        out.push(input.to_path_buf());
        return Ok(out);
    }
    if !input.is_dir() {
        bail!("input does not exist: {}", input.display());
    }
    fn walk(dir: &Path, out: &mut Vec<PathBuf>) -> Result<()> {
        for entry in std::fs::read_dir(dir)? {
            let entry = entry?;
            let path = entry.path();
            if path.is_dir() {
                walk(&path, out)?;
            } else if let Some(ext) = path.extension().and_then(|e| e.to_str()) {
                if SUPPORTED_EXTS.iter().any(|s| s.eq_ignore_ascii_case(ext)) {
                    out.push(path);
                }
            }
        }
        Ok(())
    }
    walk(input, &mut out)?;
    Ok(out)
}

fn convert_one(src: &Path, dst: &Path) -> Result<()> {
    let img = image::open(src).with_context(|| format!("decode {}", src.display()))?;
    let rgba = img.to_rgba8();
    let (w, h) = rgba.dimensions();
    let raw = rgba.as_raw();

    // Quantize to 16 colors.
    let (mut indices, palette) = quantize::quantize_16(raw, w, h);

    // Pad width to multiple of 8 by appending palette index 0 on the right.
    // (4 pixels per MAG cell × 2 cells per flag pair → width must be 8-aligned.)
    let padded_w = (w + 7) & !7;
    if padded_w != w {
        let mut padded = Vec::with_capacity((padded_w * h) as usize);
        for y in 0..h as usize {
            let row_start = y * w as usize;
            let row_end = row_start + w as usize;
            padded.extend_from_slice(&indices[row_start..row_end]);
            for _ in 0..(padded_w - w) {
                padded.push(0);
            }
        }
        indices = padded;
    }

    let memo = format!(
        "Generated by png2mag from {}",
        src.file_name().and_then(|s| s.to_str()).unwrap_or("?")
    );
    let mag = encoder::encode(&indices, padded_w as usize, h as usize, &palette, "png2mag", &memo);

    if let Some(parent) = dst.parent() {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(dst, mag).with_context(|| format!("write {}", dst.display()))?;
    Ok(())
}

fn main() -> Result<()> {
    let args: Vec<String> = std::env::args().collect();
    if args.len() != 3 {
        eprintln!("usage: png2mag <input file or dir> <output dir>");
        std::process::exit(2);
    }
    let input = PathBuf::from(&args[1]);
    let output = PathBuf::from(&args[2]);
    std::fs::create_dir_all(&output)?;

    let inputs = collect_inputs(&input)?;
    let total = inputs.len();
    if total == 0 {
        eprintln!("no supported images found under {}", input.display());
        return Ok(());
    }
    eprintln!("converting {} files...", total);

    let done = AtomicUsize::new(0);
    let failed = AtomicUsize::new(0);

    inputs.par_iter().for_each(|src| {
        // Output path: preserve filename only (flat layout); append .mag.
        let stem = src.file_stem().and_then(|s| s.to_str()).unwrap_or("out");
        // For dir input, prefix with parent dirs flattened to avoid collisions.
        let rel_name: String = if input.is_dir() {
            let rel = src.strip_prefix(&input).unwrap_or(src);
            rel.with_extension("mag")
                .to_string_lossy()
                .replace(['/', '\\'], "__")
        } else {
            format!("{stem}.mag")
        };
        let dst = output.join(&rel_name);
        match convert_one(src, &dst) {
            Ok(()) => {
                let n = done.fetch_add(1, Ordering::Relaxed) + 1;
                if n % 100 == 0 || n == total {
                    eprintln!("[{n}/{total}]");
                }
            }
            Err(e) => {
                failed.fetch_add(1, Ordering::Relaxed);
                eprintln!("FAIL {}: {e:#}", src.display());
            }
        }
    });

    let ok = done.load(Ordering::Relaxed);
    let fail = failed.load(Ordering::Relaxed);
    eprintln!("done: {ok} ok, {fail} failed");
    if fail > 0 {
        std::process::exit(1);
    }
    Ok(())
}
